name: aichara
channels:
- defaults
dependencies:
- python=3.9
- pip
- pip:
    - dash==2.6.2
    - dash-daq==0.5.0
    - gunicorn==20.1.0
    - numpy==1.23.3
    - pandas==1.5.0
    - lxml==4.5.0
    - bs4==0.0.1
    - requests==2.28.1
    - python-decouple==3.6
    - pymongo==4.2.0
    - dnspython==2.2.1
